--
-- PostgreSQL database dump
--

\restrict mubAhLwvslzlyhgsaC1PkLFWnSgtkMFGUhCHNVveDLd7VcHALsFbE3c8jMJnEl0

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Debian 16.11-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.booking DROP CONSTRAINT IF EXISTS fklex7ticy9ci7dah7e9atc98rf;
ALTER TABLE IF EXISTS ONLY public.meeting_room_equipment DROP CONSTRAINT IF EXISTS fkjaoxfm2jrsjti7467ukbn1fhr;
ALTER TABLE IF EXISTS ONLY public.booking DROP CONSTRAINT IF EXISTS fkihg9s7htmftrngqq7ls8tmu08;
ALTER TABLE IF EXISTS ONLY public.meeting_room_equipment DROP CONSTRAINT IF EXISTS fkd0juacdx1sd1qry4qoxm4wi9a;
ALTER TABLE IF EXISTS ONLY public.meeting_room DROP CONSTRAINT IF EXISTS fk9djpu29x4pheo0iy4i7jfq2sg;
ALTER TABLE IF EXISTS ONLY public.notification DROP CONSTRAINT IF EXISTS fk2k589bvvxex5a79rt1bdhnw0r;
ALTER TABLE IF EXISTS ONLY public.meeting_room DROP CONSTRAINT IF EXISTS ukh7pn94v8j64tftri1pri2aucp;
ALTER TABLE IF EXISTS ONLY public.client DROP CONSTRAINT IF EXISTS ukbfgjs3fem0hmjhvih80158x29;
ALTER TABLE IF EXISTS ONLY public.client DROP CONSTRAINT IF EXISTS ukah5c1ribskm746956okm9283n;
ALTER TABLE IF EXISTS ONLY public.notification DROP CONSTRAINT IF EXISTS notification_pkey;
ALTER TABLE IF EXISTS ONLY public.meeting_room DROP CONSTRAINT IF EXISTS meeting_room_pkey;
ALTER TABLE IF EXISTS ONLY public.meeting_room_equipment DROP CONSTRAINT IF EXISTS meeting_room_equipment_pkey;
ALTER TABLE IF EXISTS ONLY public.equipment DROP CONSTRAINT IF EXISTS equipment_pkey;
ALTER TABLE IF EXISTS ONLY public.client DROP CONSTRAINT IF EXISTS client_pkey;
ALTER TABLE IF EXISTS ONLY public.booking DROP CONSTRAINT IF EXISTS booking_pkey;
DROP TABLE IF EXISTS public.notification;
DROP TABLE IF EXISTS public.meeting_room_equipment;
DROP TABLE IF EXISTS public.meeting_room;
DROP TABLE IF EXISTS public.equipment;
DROP TABLE IF EXISTS public.client;
DROP TABLE IF EXISTS public.booking;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: booking; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.booking (
    booking_id bigint NOT NULL,
    attendees integer,
    booking_status character varying(255),
    check_in_time timestamp(6) without time zone,
    end_time timestamp(6) without time zone,
    is_active boolean,
    purpose character varying(255),
    start_time timestamp(6) without time zone,
    user_id bigint NOT NULL,
    room_id bigint NOT NULL,
    booking_code character varying(255)
);


ALTER TABLE public.booking OWNER TO postgres;

--
-- Name: booking_booking_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.booking ALTER COLUMN booking_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.client (
    user_id bigint NOT NULL,
    department character varying(255),
    email character varying(255),
    is_active boolean,
    password character varying(255),
    role character varying(255),
    user_type character varying(255),
    username character varying(255) NOT NULL
);


ALTER TABLE public.client OWNER TO postgres;

--
-- Name: client_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.client ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: equipment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.equipment (
    equipment_id bigint NOT NULL,
    description character varying(255)
);


ALTER TABLE public.equipment OWNER TO postgres;

--
-- Name: equipment_equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.equipment ALTER COLUMN equipment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipment_equipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meeting_room; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.meeting_room (
    room_id bigint NOT NULL,
    capacity integer,
    floor integer,
    has_door_control boolean,
    has_light_control boolean,
    has_ventilation_control boolean,
    image_mime character varying(255),
    image_original_name character varying(255),
    image_path character varying(255),
    is_active boolean,
    location character varying(255),
    name character varying(255),
    status character varying(255),
    client_id bigint,
    has_beamer_control boolean,
    has_blind_control boolean,
    has_vacuum_robot boolean,
    has_whiteboard boolean
);


ALTER TABLE public.meeting_room OWNER TO postgres;

--
-- Name: meeting_room_equipment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.meeting_room_equipment (
    room_id bigint NOT NULL,
    equipment_id bigint NOT NULL
);


ALTER TABLE public.meeting_room_equipment OWNER TO postgres;

--
-- Name: meeting_room_room_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.meeting_room ALTER COLUMN room_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meeting_room_room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notification (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    is_read boolean,
    type character varying(255),
    booking_id bigint,
    CONSTRAINT notification_type_check CHECK (((type)::text = ANY (ARRAY[('CONFIRMATION'::character varying)::text, ('REMINDER_START'::character varying)::text, ('REMINDER_END'::character varying)::text, ('MISSED'::character varying)::text])))
);


ALTER TABLE public.notification OWNER TO postgres;

--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: booking; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.booking (booking_id, attendees, booking_status, check_in_time, end_time, is_active, purpose, start_time, user_id, room_id, booking_code) FROM stdin;
2	\N	CONFIRMED	\N	2026-02-03 14:47:00	t		2026-02-03 14:17:00	1	3	2170-7640
1	\N	CANCELLED	\N	2026-02-03 14:50:00	f		2026-02-03 14:20:00	36	1	2245-9967
3	\N	CONFIRMED	2026-02-03 15:24:04.322312	2026-02-03 15:57:00	t		2026-02-03 15:27:00	1	1	1818-1886
4	\N	CONFIRMED	2026-02-03 15:33:12.300338	2026-02-03 16:05:00	t		2026-02-03 15:35:00	36	48	8632-2542
5	\N	COMPLETED	2026-02-03 15:39:28.662339	2026-02-03 15:41:55.544945	t		2026-02-03 15:40:00	1	3	4288-5517
\.


--
-- Data for Name: client; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.client (user_id, department, email, is_active, password, role, user_type, username) FROM stdin;
1	DiBSE	tobi@mail.com	t	$2a$10$L6Ns1J1sBYLwUGc2DHGbUOjcm5RyZ4J7XbnhvBXer/n7IfAzs8tZu	USER	STUDENT	tobi
3	MCI 1	tobi2@mail.com	t	$2a$10$bM5CFj76wSCOjOlHexzEButyJeoVTyri8mSIJxuQq55H.FVizxRKO	USER	EXTERNAL	tobi2
2	IT-Services	tobiadmin@mail.com	t	$2a$10$sAgSAZVm9dUwb9W2gdrcD.F2/ZROw6NbWaOxpEJcErEehT6J/Eu5y	ADMIN	STAFF	tobiadmin
5	\N	room_234@system.local	t	$2a$10$/X6hvDMnymJgipzdYkgxfej96bjMthk1SZa78MNu86Pp93NMl/Wye	ROOM	ROOM_SCREEN	room_234
6	\N	room_301/302@system.local	t	$2a$10$aAmXW4i8MxbjZiMXq9tMXOiLnF9esl7E9/TZkcy.dC0r0FYkRgtgK	ROOM	ROOM_SCREEN	room_301/302
7	\N	room_303@system.local	t	$2a$10$M4uD7agD2oTbRoj/XO7Tte0.4skRGptL2HlUZjUAoPKUNUfAg98w2	ROOM	ROOM_SCREEN	room_303
8	\N	room_304@system.local	t	$2a$10$pPpXetiq1aeH5tfeSGpd.e8ylawfLCg/HcPWCuLe38c0c520XZVRi	ROOM	ROOM_SCREEN	room_304
9	\N	room_305@system.local	t	$2a$10$7cL7kTqXc0sqAayGUVlx2.Ny9Sl3y8nqh5MDRZSVMuvnYvka1/nva	ROOM	ROOM_SCREEN	room_305
10	\N	room_306@system.local	t	$2a$10$8N6KoEVpw1FovPnjE5FixexMimjvJ6B4A/h8iR.IXNxBC5Q857Tni	ROOM	ROOM_SCREEN	room_306
11	\N	room_307@system.local	t	$2a$10$d/mJjGNnLMa/4r5nquHu0OS6crugB6Aji0ShJyiN2MV1Hcfh9QdWG	ROOM	ROOM_SCREEN	room_307
12	\N	room_308@system.local	t	$2a$10$ISxmCkGP7CvdWmntR5S/IeVfN.7Cs8k9Q2FvKuOiP/g2.x0YRvmWy	ROOM	ROOM_SCREEN	room_308
13	\N	room_309@system.local	t	$2a$10$Vao.Uy1IpHyZ/VYWO8hM9eJpvd6xvdv5KTTHT1jYXWRmX2H4UC49u	ROOM	ROOM_SCREEN	room_309
14	\N	room_310@system.local	t	$2a$10$C/4SiulxZsCoNl7paEnOzOM/9Vey.T9gJTKCY0gHFVNvHmxNGkNsu	ROOM	ROOM_SCREEN	room_310
15	\N	room_401/402@system.local	t	$2a$10$r1M8PFgMWRCtZK0xAC1JYuQOOTZ8CLSx0GbaKFaLQhzs5sVAN/ava	ROOM	ROOM_SCREEN	room_401/402
16	\N	room_403@system.local	t	$2a$10$83Gv1XCyF6qZFM5rYAxQReGrW/6rAFnu47lLDxJWqrtMEVdRpvzcC	ROOM	ROOM_SCREEN	room_403
17	\N	room_404@system.local	t	$2a$10$sM8dQ3dNghj/4QcckfHF3Ol6KjKavxLFHplL.odL0f3pY2scSTU5C	ROOM	ROOM_SCREEN	room_404
18	\N	room_405@system.local	t	$2a$10$buR3.JTtKVrUlmqEd6lLmuJVoe6fkvs5j1ZoPv4MyqIBTRjYGa6Ly	ROOM	ROOM_SCREEN	room_405
19	\N	room_406@system.local	t	$2a$10$BW81QUdTvo73MJSvuJPOUuY9rDQeBLqhZNYrh/eSqSgPe1OjNaNLK	ROOM	ROOM_SCREEN	room_406
20	\N	room_051/052/053@system.local	t	$2a$10$hhjpyByZKOoPFhQRUSfl4.CB9jX0ktPa.zev0gnjpiWdlrgkr.MQW	ROOM	ROOM_SCREEN	room_051/052/053
21	\N	room_162@system.local	t	$2a$10$vTUH43ZXMRQjJ9nHGyHYdedu7591nMo.fgitNqXyE/PRvYsV1w72u	ROOM	ROOM_SCREEN	room_162
22	\N	room_163@system.local	t	$2a$10$vN1DdtqXK29aO0Wwbmil8uau9cO0Y2ed/i2JKFPUUjPHgwoQgK46q	ROOM	ROOM_SCREEN	room_163
23	\N	room_164@system.local	t	$2a$10$Jk56SzebWHtg26pLclYH8uw83HzKWZ0l06aPhDEHjWZot7caOaFEa	ROOM	ROOM_SCREEN	room_164
24	\N	room_551/552@system.local	t	$2a$10$rgl6mw3rxWxNwKrK9JhN4.JmDtnCkM5gXnmTUZvAsvNP.LpO.tP7W	ROOM	ROOM_SCREEN	room_551/552
25	\N	room_011@system.local	t	$2a$10$UIMMlJCSyGsgg9UX/UsviO5MY0EPVHlA218YOmDHVFzyXfh5QkhCa	ROOM	ROOM_SCREEN	room_011
26	\N	room_012@system.local	t	$2a$10$7m.O0amaSejJw/5OmFdjQOLe71y5lTAw6SpVTncrWbdfsOOrvbq9y	ROOM	ROOM_SCREEN	room_012
27	\N	room_013@system.local	t	$2a$10$kTd0iTpMMMs84zlzx6Z3M.ab7w68g8K8T2d7R8CBiXMkRtHS7IIn6	ROOM	ROOM_SCREEN	room_013
28	\N	room_014@system.local	t	$2a$10$HqoyqTi0e.QShMY0PfRuE.tBbHVGG1V9R1AMJwwbJqeqPbUA5s29O	ROOM	ROOM_SCREEN	room_014
29	\N	room_111@system.local	t	$2a$10$tMGa9HCEOo7bvYY5atA9Y.77URoyQDpvI7OS9qiU8liGGhFVU6usC	ROOM	ROOM_SCREEN	room_111
30	\N	room_112/113@system.local	t	$2a$10$bBzXiK10BRobXXCJ6upP7.d7/on6GoAmc.v4gnfcDymWQ7/V3jHsW	ROOM	ROOM_SCREEN	room_112/113
31	DiBSE	peter@mail.com	t	$2a$10$3cH8cs/yY3rK/XFolm1vV.kHbRN152KlWUr61nR5Aswzhgn1.7qnu	USER	STUDENT	peter
32	DiBSE	matthias@mail.com	t	$2a$10$ixw77LM6v8Ak6pvIZZJe.uK9M4vAbY3aeLFdP5cK8L2dzVxwbUfRm	USER	STUDENT	matthias
33	DiBSE	alessandro@mail.com	t	$2a$10$shrut4r13COsRucrwMTNGO/.9Xj9GQQGfypdWXQuOGLQNZywC5dui	USER	STUDENT	alessandro
34	DiBSE	plamena@mail.com	t	$2a$10$2ouvqI83qVxy.bPg4LPFy.QbJBDBc0HA8D2EDyBexL7BZaaogidYK	USER	STUDENT	plamena
36	IT-Services	admin@mail.com	t	$2a$10$B0hryWKFVd13cYBuX/yYl.N6xsztsIH3pztdt.l8/45bu8NQ4Zbkq	ADMIN	STAFF	admin
35	IT-Services	nicoadmin@mail.com	f	$2a$10$E7r8zAL8QZZ1HWXjkPD3ie9LgUAlnaQ0lZZKvB3lWHD3iMqkBlnWO	ADMIN	STAFF	nicoadmin
4	DiBSE	nico@mail.com	t	$2a$10$2/DEkdQUJ52eEjk/t775b.Jb.0lJEVw49C609n.jMOdueamIqM5NC	ADMIN	STAFF	nico
37	\N	room_4b-001@system.local	t	$2a$10$kSesd0caAbdS6w6HtVm/9.Rdu09F.C1qSxyAy98wWbxwYon0KM9ym	ROOM	ROOM_SCREEN	room_4b-001
38	\N	room_4b-003@system.local	t	$2a$10$45bIJ9lHEdVJHA4jdg3apOf0F3W1axJH5fs2ix8w00JUJQVFc0LTm	ROOM	ROOM_SCREEN	room_4b-003
39	\N	room_4b-005@system.local	t	$2a$10$00YQwY19Vqo2LAwfFbdAdOdfiJL2P7hQ7a4XGuMwsD6R5DRVY8yHe	ROOM	ROOM_SCREEN	room_4b-005
40	\N	room_4b-006@system.local	t	$2a$10$40T8b9.YWssiO18qlbSylubWp72yQAmEfauefzdgjXMiady3psTzG	ROOM	ROOM_SCREEN	room_4b-006
41	\N	room_4b-007@system.local	t	$2a$10$dJHxl7oG9vF2ivpsgdf.FOvSOfKouJTt95wCqXZ1EorcyCGUtbfGe	ROOM	ROOM_SCREEN	room_4b-007
42	\N	room_4b-008@system.local	t	$2a$10$urjhuxgpMdZ3Gpeg1XiBLO4J679eK32T3Ej6BME5aZqBv5dtOWVb.	ROOM	ROOM_SCREEN	room_4b-008
43	\N	room_4a-020@system.local	t	$2a$10$yvzv7dwN2clhoQaMKGCvNe6WDc1h278vUB9cw5j2g7G2N.zOZKLYm	ROOM	ROOM_SCREEN	room_4a-020
44	\N	room_4a-024@system.local	t	$2a$10$rX3UeythlEUB3EtCiepCe.CZkQrGQCiM/KB5AAwl1kGhZHosQ.nYW	ROOM	ROOM_SCREEN	room_4a-024
45	\N	room_4a-027@system.local	t	$2a$10$36LUnGO.Swvt.psOnx2Biul7l2Q3IpQiRjAYSQ/9HrHXEIQBDrbca	ROOM	ROOM_SCREEN	room_4a-027
46	\N	room_1a-135@system.local	t	$2a$10$BQky30Ukz68khnQHHNilO.yp/w.ct83WuRKB4PbLs/x1zs7YV3Scm	ROOM	ROOM_SCREEN	room_1a-135
47	\N	room_4b-115@system.local	t	$2a$10$fqbt643.6Fiu/6CuoRwmq.qUo8jtWsIjJFXtaHnyAhyotpUbhzUnq	ROOM	ROOM_SCREEN	room_4b-115
48	\N	room_4a-393@system.local	t	$2a$10$beX.jgH2EpjTHKt3rdyHw.Zs52sG4AmM/WWkauvV5QgpzDhMiHzu2	ROOM	ROOM_SCREEN	room_4a-393
49	\N	room_4a-438@system.local	t	$2a$10$trRs1k.B0LEF4.vNDjJArOmiWw2EXOtoQNmzMY6xg1K9b0Rpyeowe	ROOM	ROOM_SCREEN	room_4a-438
50	\N	room_4a-439@system.local	t	$2a$10$Gvp.kgEaPXcdQ3qgv.2bdutqo0qq4KJBskkMWAXWqIJHnv9NDYGEu	ROOM	ROOM_SCREEN	room_4a-439
51	\N	room_4c-501@system.local	t	$2a$10$RhnQTcOYdCZlE0WrIfJoduzPUcKOc/kryYAYBLJIiDXAy5gm.lJ06	ROOM	ROOM_SCREEN	room_4c-501
52	\N	room_4c-502@system.local	t	$2a$10$vmEDcTMiddodvDUNNI6/uuXWYqAHe.GiknScdTzZTgCl.yPB7loGW	ROOM	ROOM_SCREEN	room_4c-502
53	\N	room_4c-503@system.local	t	$2a$10$NQsqozT1PTeyLfTBqI744eXErr/0QSZHxKe2hmB0aGQ8EPUxmdNoK	ROOM	ROOM_SCREEN	room_4c-503
54	\N	room_4c-504@system.local	t	$2a$10$P9Oj9S3G8PhSdqjCdFfs.OpZDS/HBMQgoEGjFk7sC1oK9tn11byYm	ROOM	ROOM_SCREEN	room_4c-504
55	\N	room_4c-505@system.local	t	$2a$10$EWkhoRGFItwHF90Z7zjxguWRvt.DwCYQXvnaSTp/A16zfiLs3Pi0i	ROOM	ROOM_SCREEN	room_4c-505
56	\N	room_181@system.local	t	$2a$10$HnqFs9ZvAf8GyWbMpzcmSO5Mls08XQseAPDlq1pfXhl7YWTMFGgxy	ROOM	ROOM_SCREEN	room_181
57	\N	room_182@system.local	t	$2a$10$9bW45bdGPETRz8rs4Fjkruzc/OSds/t7WwKA6zi3ixD17Bn5enGnS	ROOM	ROOM_SCREEN	room_182
58	\N	room_183@system.local	t	$2a$10$zfJyMy3KMq16tk4GdqpfdOMW1XN1wTsmnTqNGwLGi8a1saSjsXsA2	ROOM	ROOM_SCREEN	room_183
59	\N	room_184@system.local	t	$2a$10$3Ph5jcfIUneAQMRVsjr3ZOgpwcnw1kPUJZBRXYDwMi1Svb4NidSwC	ROOM	ROOM_SCREEN	room_184
60	\N	room_185@system.local	t	$2a$10$U9WTEqVKy.hDr4N8UbMapu0smDkPfS.p6O505eKrG2LAP6aYBHCvK	ROOM	ROOM_SCREEN	room_185
61	\N	room_283@system.local	t	$2a$10$VwqTjB2Gi1BsRD5mp5nKbOCSK.C0s3IJT3A7lLp.V76bTyR4VEAKq	ROOM	ROOM_SCREEN	room_283
\.


--
-- Data for Name: equipment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.equipment (equipment_id, description) FROM stdin;
1	Door Control
2	Blind Control
3	Light Control
4	Ventilation Control
5	Beamer Control
6	Whiteboard
7	Vacuum Robot
\.


--
-- Data for Name: meeting_room; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.meeting_room (room_id, capacity, floor, has_door_control, has_light_control, has_ventilation_control, image_mime, image_original_name, image_path, is_active, location, name, status, client_id, has_beamer_control, has_blind_control, has_vacuum_robot, has_whiteboard) FROM stdin;
28	30	0	f	t	f	\N	\N	\N	t	MCI IV	4B-003	ACTIVE	38	f	f	f	f
1	26	2	t	t	t	\N	\N	\N	t	MCI I	234	ACTIVE	5	t	t	t	t
4	54	3	t	t	t	\N	\N	\N	t	MCI I	304	ACTIVE	8	t	t	t	t
6	56	3	f	t	f	\N	\N	\N	t	MCI I	306	ACTIVE	10	f	f	f	f
7	32	3	f	t	f	\N	\N	\N	t	MCI I	307	ACTIVE	11	f	f	f	f
8	18	3	f	t	f	\N	\N	\N	t	MCI I	308	ACTIVE	12	f	f	f	f
9	45	3	f	t	f	\N	\N	\N	t	MCI I	309	ACTIVE	13	f	f	f	f
10	32	3	f	t	f	\N	\N	\N	t	MCI I	310	ACTIVE	14	f	f	f	f
11	20	4	f	t	f	\N	\N	\N	t	MCI I	401/402	ACTIVE	15	f	f	f	f
12	28	4	f	t	f	\N	\N	\N	t	MCI I	403	ACTIVE	16	f	f	f	f
13	28	4	f	t	f	\N	\N	\N	t	MCI I	404	ACTIVE	17	f	f	f	f
14	28	4	f	t	f	\N	\N	\N	t	MCI I	405	ACTIVE	18	f	f	f	f
15	32	4	f	t	f	\N	\N	\N	t	MCI I	406	ACTIVE	19	f	f	f	f
16	100	0	f	t	f	\N	\N	\N	t	MCI II	051/052/053	ACTIVE	20	f	f	f	f
17	8	1	f	t	f	\N	\N	\N	t	MCI II	162	ACTIVE	21	f	f	f	f
18	8	1	f	t	f	\N	\N	\N	t	MCI II	163	ACTIVE	22	f	f	f	f
19	12	1	f	t	f	\N	\N	\N	t	MCI II	164	ACTIVE	23	f	f	f	f
20	94	5	f	t	f	\N	\N	\N	t	MCI II	551/552	ACTIVE	24	f	f	f	f
21	54	0	f	t	f	\N	\N	\N	t	MCI III	011	ACTIVE	25	f	f	f	f
22	54	0	f	t	f	\N	\N	\N	t	MCI III	012	ACTIVE	26	f	f	f	f
23	54	0	f	t	f	\N	\N	\N	t	MCI III	013	ACTIVE	27	f	f	f	f
24	30	0	f	t	f	\N	\N	\N	t	MCI III	014	ACTIVE	28	f	f	f	f
25	54	1	f	t	f	\N	\N	\N	t	MCI III	111	ACTIVE	29	f	f	f	f
26	90	1	f	t	f	\N	\N	\N	t	MCI III	112/113	ACTIVE	30	f	f	f	f
27	29	0	f	t	f	\N	\N	\N	t	MCI IV	4B-001	ACTIVE	37	f	f	f	f
29	23	0	f	t	f	\N	\N	\N	t	MCI IV	4B-005	ACTIVE	39	f	f	f	f
30	33	0	f	t	f	\N	\N	\N	t	MCI IV	4B-006	ACTIVE	40	f	f	f	f
31	30	0	f	t	f	\N	\N	\N	t	MCI IV	4B-007	ACTIVE	41	f	f	f	f
32	16	0	f	t	f	\N	\N	\N	t	MCI IV	4B-008	ACTIVE	42	f	f	f	f
33	58	0	f	t	f	\N	\N	\N	t	MCI IV	4A-020	ACTIVE	43	f	f	f	f
34	68	0	f	t	f	\N	\N	\N	t	MCI IV	4A-024	ACTIVE	44	f	f	f	f
35	60	0	f	t	f	\N	\N	\N	t	MCI IV	4A-027	ACTIVE	45	f	f	f	f
36	45	1	f	t	f	\N	\N	\N	t	MCI IV	1A-135	ACTIVE	46	f	f	f	f
38	48	3	f	t	f	\N	\N	\N	t	MCI IV	4A-393	ACTIVE	48	f	f	f	f
39	36	4	f	t	f	\N	\N	\N	t	MCI IV	4A-438	ACTIVE	49	f	f	f	f
40	68	4	f	t	f	\N	\N	\N	t	MCI IV	4A-439	ACTIVE	50	f	f	f	f
37	22	1	f	t	f	\N	\N	\N	t	MCI IV	4B-115	ACTIVE	47	f	f	f	f
41	12	5	f	t	f	\N	\N	\N	t	MCI IV	4C-501	ACTIVE	51	f	f	f	f
42	25	5	f	t	f	\N	\N	\N	t	MCI IV	4C-502	ACTIVE	52	f	f	f	f
43	25	5	f	t	f	\N	\N	\N	t	MCI IV	4C-503	ACTIVE	53	f	f	f	f
44	27	5	f	t	f	\N	\N	\N	t	MCI IV	4C-504	ACTIVE	54	f	f	f	f
45	45	5	f	t	f	\N	\N	\N	t	MCI IV	4C-505	ACTIVE	55	f	f	f	f
46	40	1	f	t	f	\N	\N	\N	t	MCI V	181	ACTIVE	56	f	f	f	f
47	40	1	f	t	f	\N	\N	\N	t	MCI V	182	ACTIVE	57	f	f	f	f
48	40	1	f	t	f	\N	\N	\N	t	MCI V	183	ACTIVE	58	f	f	f	f
3	54	3	t	t	f	\N	\N	\N	t	MCI I	303	ACTIVE	7	f	t	t	f
2	132	3	f	t	f	\N	\N	\N	t	MCI I	301/302	ACTIVE	6	f	f	f	f
49	44	1	f	t	f	\N	\N	\N	t	MCI V	184	ACTIVE	59	f	f	f	f
50	52	1	f	t	f	\N	\N	\N	t	MCI V	185	ACTIVE	60	f	f	f	f
51	40	2	f	t	f	\N	\N	\N	t	MCI V	283	ACTIVE	61	f	f	f	f
5	60	3	f	t	f	\N	\N	\N	t	MCI I	305	ACTIVE	9	f	f	f	f
\.


--
-- Data for Name: meeting_room_equipment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.meeting_room_equipment (room_id, equipment_id) FROM stdin;
1	5
1	6
1	3
1	7
1	4
1	1
1	2
3	2
3	1
3	3
4	6
4	1
4	3
4	5
4	4
4	7
4	2
6	3
7	3
8	3
9	3
10	3
11	3
12	3
13	3
14	3
15	3
16	3
17	3
18	3
19	3
20	3
21	3
22	3
23	3
24	3
25	3
26	3
27	3
28	3
29	3
30	3
31	3
32	3
33	3
34	3
35	3
36	3
38	3
39	3
40	3
37	3
41	3
42	3
43	3
44	3
45	3
46	3
47	3
48	3
3	7
2	3
49	3
50	3
51	3
5	3
\.


--
-- Data for Name: notification; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notification (id, created_at, is_read, type, booking_id) FROM stdin;
3	2026-02-03 14:42:00.018045	f	REMINDER_END	2
4	2026-02-03 15:23:16.364102	f	CONFIRMATION	3
5	2026-02-03 15:23:16.367822	f	REMINDER_START	3
6	2026-02-03 15:32:46.758294	f	CONFIRMATION	4
7	2026-02-03 15:32:46.760899	f	REMINDER_START	4
8	2026-02-03 15:39:16.005847	f	CONFIRMATION	5
9	2026-02-03 15:39:16.00793	f	REMINDER_START	5
\.


--
-- Name: booking_booking_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.booking_booking_id_seq', 5, true);


--
-- Name: client_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.client_user_id_seq', 61, true);


--
-- Name: equipment_equipment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.equipment_equipment_id_seq', 7, true);


--
-- Name: meeting_room_room_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.meeting_room_room_id_seq', 51, true);


--
-- Name: notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notification_id_seq', 9, true);


--
-- Name: booking booking_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT booking_pkey PRIMARY KEY (booking_id);


--
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (user_id);


--
-- Name: equipment equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_pkey PRIMARY KEY (equipment_id);


--
-- Name: meeting_room_equipment meeting_room_equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_room_equipment
    ADD CONSTRAINT meeting_room_equipment_pkey PRIMARY KEY (room_id, equipment_id);


--
-- Name: meeting_room meeting_room_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_room
    ADD CONSTRAINT meeting_room_pkey PRIMARY KEY (room_id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: client ukah5c1ribskm746956okm9283n; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT ukah5c1ribskm746956okm9283n UNIQUE (username);


--
-- Name: client ukbfgjs3fem0hmjhvih80158x29; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT ukbfgjs3fem0hmjhvih80158x29 UNIQUE (email);


--
-- Name: meeting_room ukh7pn94v8j64tftri1pri2aucp; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_room
    ADD CONSTRAINT ukh7pn94v8j64tftri1pri2aucp UNIQUE (client_id);


--
-- Name: notification fk2k589bvvxex5a79rt1bdhnw0r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fk2k589bvvxex5a79rt1bdhnw0r FOREIGN KEY (booking_id) REFERENCES public.booking(booking_id);


--
-- Name: meeting_room fk9djpu29x4pheo0iy4i7jfq2sg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_room
    ADD CONSTRAINT fk9djpu29x4pheo0iy4i7jfq2sg FOREIGN KEY (client_id) REFERENCES public.client(user_id);


--
-- Name: meeting_room_equipment fkd0juacdx1sd1qry4qoxm4wi9a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_room_equipment
    ADD CONSTRAINT fkd0juacdx1sd1qry4qoxm4wi9a FOREIGN KEY (room_id) REFERENCES public.meeting_room(room_id);


--
-- Name: booking fkihg9s7htmftrngqq7ls8tmu08; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fkihg9s7htmftrngqq7ls8tmu08 FOREIGN KEY (room_id) REFERENCES public.meeting_room(room_id);


--
-- Name: meeting_room_equipment fkjaoxfm2jrsjti7467ukbn1fhr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_room_equipment
    ADD CONSTRAINT fkjaoxfm2jrsjti7467ukbn1fhr FOREIGN KEY (equipment_id) REFERENCES public.equipment(equipment_id);


--
-- Name: booking fklex7ticy9ci7dah7e9atc98rf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fklex7ticy9ci7dah7e9atc98rf FOREIGN KEY (user_id) REFERENCES public.client(user_id);


--
-- PostgreSQL database dump complete
--

\unrestrict mubAhLwvslzlyhgsaC1PkLFWnSgtkMFGUhCHNVveDLd7VcHALsFbE3c8jMJnEl0

