--
-- PostgreSQL database dump
--

\restrict m7k88nbBUPsQLxHmH3KdQe7qTmEhwFtdJry7rl9udgxHcpCL3wWuuWWYYguZLnc

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11 (Debian 16.11-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.booking DROP CONSTRAINT IF EXISTS fklex7ticy9ci7dah7e9atc98rf;
ALTER TABLE IF EXISTS ONLY public.meeting_room_equipment DROP CONSTRAINT IF EXISTS fkjaoxfm2jrsjti7467ukbn1fhr;
ALTER TABLE IF EXISTS ONLY public.booking DROP CONSTRAINT IF EXISTS fkihg9s7htmftrngqq7ls8tmu08;
ALTER TABLE IF EXISTS ONLY public.meeting_room_equipment DROP CONSTRAINT IF EXISTS fkd0juacdx1sd1qry4qoxm4wi9a;
ALTER TABLE IF EXISTS ONLY public.meeting_room DROP CONSTRAINT IF EXISTS fk9djpu29x4pheo0iy4i7jfq2sg;
ALTER TABLE IF EXISTS ONLY public.meeting_room DROP CONSTRAINT IF EXISTS ukh7pn94v8j64tftri1pri2aucp;
ALTER TABLE IF EXISTS ONLY public.client DROP CONSTRAINT IF EXISTS ukbfgjs3fem0hmjhvih80158x29;
ALTER TABLE IF EXISTS ONLY public.client DROP CONSTRAINT IF EXISTS ukah5c1ribskm746956okm9283n;
ALTER TABLE IF EXISTS ONLY public.meeting_room DROP CONSTRAINT IF EXISTS meeting_room_pkey;
ALTER TABLE IF EXISTS ONLY public.meeting_room_equipment DROP CONSTRAINT IF EXISTS meeting_room_equipment_pkey;
ALTER TABLE IF EXISTS ONLY public.equipment DROP CONSTRAINT IF EXISTS equipment_pkey;
ALTER TABLE IF EXISTS ONLY public.client DROP CONSTRAINT IF EXISTS client_pkey;
ALTER TABLE IF EXISTS ONLY public.booking DROP CONSTRAINT IF EXISTS booking_pkey;
DROP TABLE IF EXISTS public.meeting_room_equipment;
DROP TABLE IF EXISTS public.meeting_room;
DROP TABLE IF EXISTS public.equipment;
DROP TABLE IF EXISTS public.client;
DROP TABLE IF EXISTS public.booking;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: booking; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.booking (
    booking_id bigint NOT NULL,
    attendees integer,
    booking_status character varying(255),
    check_in_time timestamp(6) without time zone,
    end_time timestamp(6) without time zone,
    is_active boolean,
    purpose character varying(255),
    start_time timestamp(6) without time zone,
    user_id bigint NOT NULL,
    room_id bigint NOT NULL
);


ALTER TABLE public.booking OWNER TO postgres;

--
-- Name: booking_booking_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.booking ALTER COLUMN booking_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_booking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.client (
    user_id bigint NOT NULL,
    department character varying(255),
    email character varying(255),
    is_active boolean,
    password character varying(255),
    role character varying(255),
    user_type character varying(255),
    username character varying(255) NOT NULL
);


ALTER TABLE public.client OWNER TO postgres;

--
-- Name: client_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.client ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: equipment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.equipment (
    equipment_id bigint NOT NULL,
    description character varying(255)
);


ALTER TABLE public.equipment OWNER TO postgres;

--
-- Name: equipment_equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.equipment ALTER COLUMN equipment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipment_equipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: meeting_room; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.meeting_room (
    room_id bigint NOT NULL,
    capacity integer,
    floor integer,
    has_door_control boolean,
    has_light_control boolean,
    has_ventilation_control boolean,
    image_mime character varying(255),
    image_original_name character varying(255),
    image_path character varying(255),
    is_active boolean,
    location character varying(255),
    name character varying(255),
    status character varying(255),
    client_id bigint
);


ALTER TABLE public.meeting_room OWNER TO postgres;

--
-- Name: meeting_room_equipment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.meeting_room_equipment (
    room_id bigint NOT NULL,
    equipment_id bigint NOT NULL
);


ALTER TABLE public.meeting_room_equipment OWNER TO postgres;

--
-- Name: meeting_room_room_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.meeting_room ALTER COLUMN room_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.meeting_room_room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: booking; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.booking (booking_id, attendees, booking_status, check_in_time, end_time, is_active, purpose, start_time, user_id, room_id) FROM stdin;
\.


--
-- Data for Name: client; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.client (user_id, department, email, is_active, password, role, user_type, username) FROM stdin;
1	DiBSE	tobi@mail.com	t	$2a$10$L6Ns1J1sBYLwUGc2DHGbUOjcm5RyZ4J7XbnhvBXer/n7IfAzs8tZu	USER	STUDENT	tobi
2	IT-Services	tobiadmin@mail.com	t	$2a$10$sAgSAZVm9dUwb9W2gdrcD.F2/ZROw6NbWaOxpEJcErEehT6J/Eu5y	USER	STAFF	tobiadmin
3	MCI 1	tobi2@mail.com	t	$2a$10$bM5CFj76wSCOjOlHexzEButyJeoVTyri8mSIJxuQq55H.FVizxRKO	USER	EXTERNAL	tobi2
\.


--
-- Data for Name: equipment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.equipment (equipment_id, description) FROM stdin;
\.


--
-- Data for Name: meeting_room; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.meeting_room (room_id, capacity, floor, has_door_control, has_light_control, has_ventilation_control, image_mime, image_original_name, image_path, is_active, location, name, status, client_id) FROM stdin;
\.


--
-- Data for Name: meeting_room_equipment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.meeting_room_equipment (room_id, equipment_id) FROM stdin;
\.


--
-- Name: booking_booking_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.booking_booking_id_seq', 1, false);


--
-- Name: client_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.client_user_id_seq', 3, true);


--
-- Name: equipment_equipment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.equipment_equipment_id_seq', 1, false);


--
-- Name: meeting_room_room_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.meeting_room_room_id_seq', 1, false);


--
-- Name: booking booking_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT booking_pkey PRIMARY KEY (booking_id);


--
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (user_id);


--
-- Name: equipment equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_pkey PRIMARY KEY (equipment_id);


--
-- Name: meeting_room_equipment meeting_room_equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_room_equipment
    ADD CONSTRAINT meeting_room_equipment_pkey PRIMARY KEY (room_id, equipment_id);


--
-- Name: meeting_room meeting_room_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_room
    ADD CONSTRAINT meeting_room_pkey PRIMARY KEY (room_id);


--
-- Name: client ukah5c1ribskm746956okm9283n; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT ukah5c1ribskm746956okm9283n UNIQUE (username);


--
-- Name: client ukbfgjs3fem0hmjhvih80158x29; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT ukbfgjs3fem0hmjhvih80158x29 UNIQUE (email);


--
-- Name: meeting_room ukh7pn94v8j64tftri1pri2aucp; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_room
    ADD CONSTRAINT ukh7pn94v8j64tftri1pri2aucp UNIQUE (client_id);


--
-- Name: meeting_room fk9djpu29x4pheo0iy4i7jfq2sg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_room
    ADD CONSTRAINT fk9djpu29x4pheo0iy4i7jfq2sg FOREIGN KEY (client_id) REFERENCES public.client(user_id);


--
-- Name: meeting_room_equipment fkd0juacdx1sd1qry4qoxm4wi9a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_room_equipment
    ADD CONSTRAINT fkd0juacdx1sd1qry4qoxm4wi9a FOREIGN KEY (room_id) REFERENCES public.meeting_room(room_id);


--
-- Name: booking fkihg9s7htmftrngqq7ls8tmu08; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fkihg9s7htmftrngqq7ls8tmu08 FOREIGN KEY (room_id) REFERENCES public.meeting_room(room_id);


--
-- Name: meeting_room_equipment fkjaoxfm2jrsjti7467ukbn1fhr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.meeting_room_equipment
    ADD CONSTRAINT fkjaoxfm2jrsjti7467ukbn1fhr FOREIGN KEY (equipment_id) REFERENCES public.equipment(equipment_id);


--
-- Name: booking fklex7ticy9ci7dah7e9atc98rf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.booking
    ADD CONSTRAINT fklex7ticy9ci7dah7e9atc98rf FOREIGN KEY (user_id) REFERENCES public.client(user_id);


--
-- PostgreSQL database dump complete
--

\unrestrict m7k88nbBUPsQLxHmH3KdQe7qTmEhwFtdJry7rl9udgxHcpCL3wWuuWWYYguZLnc

